version: 0.2

phases:
  pre_build:
    commands:
    - echo Run 'build / lint / test'
    - docker build -t sdk-js . 
    - docker run sdk-js yarn build
    - docker run sdk-js yarn lint
    - docker run sdk-js yarn testCI
    - node_id=$(docker run -d --rm -p 9944:9944 kiltprotocol/mashnet-node ./target/release/mashnet-node --dev --ws-port 9944 --ws-external)
    - docker run --rm --net="host" sdk-js yarn test_integration
    - docker stop $node_id
    - echo 'build / lint / test' successful!  
  build:
    commands:
    - echo Build started on `date`, afterwards pushing to NPM registry https://www.npmjs.com/org/kiltprotocol
    - docker run -e NPM_USER='kiltbot' -e NPM_PASS="${NPM_PASS}" -e NPM_EMAIL='bot@kilt-protocol.io' -e NPM_SCOPE='@kiltprotocol' -e NPM_RC_FILE='./.npmrc' sdk-js yarn buildAndPublish
    - echo Build and publish completed on `date`
