name: Publish package to github packages
on:
  push:
    branches:
      - develop
      - tw-835-workspaces
    # paths:
    #   - '**/*.ts'
    #   - 'package.json'
    #   - '!**/*.spec.ts'
    #   - '!**/__integrationtests__'
    #   - '!**/__mocks__'
    #   - '!docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]') && github.repository == 'kiltprotocol/sdk-js'"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn install --immutable
      - name: Set package version as prerelease
        run: yarn run version prerelease
      - name: Publish to npm
        run: yarn run publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - name: Commit files
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "[CI Skip] ci: publish prerelease" -n
          git push
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GH_PAT }}
      #     branch: ${{ github.ref }}

  dispatch:
    needs: build
    strategy:
      matrix:
        repo: ['KILTprotocol/kilt-workshop-101', 'KILTprotocol/demo-client']
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: sdk-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "github": ${{ toJson(github) }}}'
