name: Publish prerelease package to npm
on:
  push:
    branches:
      - develop
    paths:
      - "**/*.ts"
      - "package.json"
      - "**/package.json"
      - "!**/*.spec.ts"
      - "!**/__integrationtests__"
      - "!**/__mocks__"
      - "!docs/**"
jobs:
  build:
    runs-on: ubuntu-latest
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]') && github.repository == 'kiltprotocol/sdk-js'"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: Install dependencies
        run: yarn install --immutable
      - name: Bump prerelease version of root package
        run: yarn version prerelease
      - name: Get current package version
        run: package_version="$(node -pe "require('./package.json').version")"
      - name: Set all other packages to same version
        run: yarn run version $package_version
      - name: Build packages
        run: yarn run build
      - name: Publish to npm
        run: yarn run publish --tag dev
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.npm_token }}
      - name: Commit files
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "[CI Skip] ci: publish prerelease" -n
          git push
  dispatch:
    needs: build
    strategy:
      matrix:
        repo:
          [
            "KILTprotocol/kilt-workshop-101",
            "KILTprotocol/demo-client",
            "KILTprotocol/prototype-services",
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: sdk-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "github": ${{ toJson(github) }}}'
