name: Publish package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn test:ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build packages
        run: yarn run build
      - name: Publish to NPM
        run: yarn run publish --tag latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.npm_token}}
