name: Lint and Test

on:
  push:
    branches: 
      - develop
      - master
    tags:
      - '*'
  pull_request:
    branches: 
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build and test
      run: |
        yarn install --frozen-lockfile
        yarn lint
        yarn test:ci
        yarn build
      env:
        CI: true

  integration_test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1
        - name: Use Node.js 10
          uses: actions/setup-node@v1
          with:
            node-version: 10
        - name: yarn install and test
          run: |
            yarn install --frozen-lockfile
            docker run -d --rm -p 9944:9944 kiltprotocol/mashnet-node ./target/release/mashnet-node --dev --ws-port 9944 --ws-external
            yarn test:integration
            docker stop $(docker ps -f ancestor=kiltprotocol/mashnet-node -q)
