name: Lint and Test

on:
  push:
    branches:
      - develop
      - master
      - gh-workflow-service
    tags:
      - '*'
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build and test
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test:ci
          yarn build
        env:
          CI: true

  integration_test:
    runs-on: ubuntu-latest

    services:
      mashnet-node:
        image: kiltprotocol/mashnet-node:develop
        ports:
          - 9944:9944
        options: --name=develop-node

    steps:
      - name: start dev chain
        run: |
          docker start develop-node
          docker exec -d develop-node ./target/release/mashnet-node --dev --ws-port 9944 --ws-external

      - uses: actions/checkout@v1

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: yarn install and test
        timeout-minutes: 60
        run: |
          yarn install --frozen-lockfile
          yarn test:integration:run

  run_example:
    runs-on: ubuntu-latest

    services:
      mashnet-node:
        image: kiltprotocol/mashnet-node:develop
        ports:
          - 9944:9944
        options: --name=develop-node

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: start dev chain
        run: |
          docker start develop-node
          docker exec -d develop-node ./target/release/mashnet-node --dev --ws-port 9944 --ws-external

      - name: yarn install and test
        timeout-minutes: 10
        run: |
          yarn install --frozen-lockfile
          yarn ts-node docs/example.ts

  run_getting-started:
    runs-on: ubuntu-latest

    services:
      mashnet-node:
        image: kiltprotocol/mashnet-node:develop
        ports:
          - 9944:9944
        options: --name=develop-node

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: start dev chain
        run: |
          docker start develop-node
          docker exec -d develop-node ./target/release/mashnet-node --dev --ws-port 9944 --ws-external

      - name: yarn install and test
        timeout-minutes: 10
        run: |
          yarn install --frozen-lockfile
          yarn ts-node docs/getting-started.ts
